### ISSUE TITLE
`fieldTag` is not decodable

### ISSUE THREAD

**Issue by ChiChou** [goretk/pygore#5]
https://github.com/goretk/pygore/blob/a8a12f44bd85000889d98330dcc85f20bea041e6/pygore/lib.py#L374

It tries to decode fieldTag to a string, but AFAIK this field is not always UTF8 decodable and this exception will be thrown:

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3: invalid start byte

Here's some sample from my binary:

```
b'\tPrecision\x01'
b''
b'\nVolumeName\x01'
b'\x0bBuckHashSys\x01'
b'\x0eCopyrightYears\x01'
b'\x10CurvePreferences\x01'
b'\x0eMulticastAddrs\x01'
b''
b''
b''
b''
b''
b''
b'\x16ListPortforwardHandler\x01'
b'\x07Nscount\x01'
```

**Comment by ChiChou** [comment]
I guess it should keep this property as is?

**Comment by TcM1911** [comment]
@ChiChou, can you provide a test case that fails?
```python
>>> test = [b'\tPrecision\x01', b'', b'\nVolumeName\x01', b'\x0bBuckHashSys\x01', b'\x0eCopyrightYears\x01', b'\x10CurvePreferences\x01', b'\x0eMulticastAddrs\x01', b'\x16ListPortforwardHandler\x01', b'\x07Nscount\x01']
>>> i = 0
>>> for t in test:
...     print('{}: {}'.format(i, str(t.decode('utf-8'))))
...     i += 1
... 
0:      Precision
1: 
2: 
VolumeName
3: 
   BuckHashSys
4: CopyrightYears
5: CurvePreferences
6: MulticastAddrs
7: ListPortforwardHandler
8: Nscount
```

Does it work with [redress](hhttps://github.com/goretk/redress/releases). Does it print the struct tags correctly when you run it with the `-struct` flag? If it doesn't, it might be a problem with the parsing of the file/data.

**Comment by ChiChou** [comment]
The test case:

```
b'\x02op\x80\xff'
```

If you need the executable sample, please mail to codecolorist () gmail

**Comment by TcM1911** [comment]
Version 0.2.1 released with a fix.
