### ISSUE TITLE
Add go buildid to compiler info

### ISSUE THREAD

**Issue by stevemk14ebr** [goretk/pygore#7]
```
goBuildPrefix = b'\xff Go build ID: \"'
goBuildEnd = b'\"\n \xff'

# the go buildId is a hex formatted sha-1 go string (utf-8)
goBuildId = buf[buf.index(goBuildPrefix) + len(goBuildPrefix):buf.index(goBuildEnd)]
```

**Comment by TcM1911** [comment]
The cleanest way for this is to implement it in the core library and just add it as an attribute to the "file". 
I've opened https://github.com/goretk/gore/issues/7 to track it in the core library.

**Comment by TcM1911** [comment]
Delivered in v0.3.0.
