### ISSUE TITLE
Expose fieldAnon flag

### ISSUE THREAD

**Issue by stevemk14ebr** [goretk/pygore#9]
This is not exposed in the python lib. https://github.com/goretk/gore/blob/6a6a317e9e6de9a3e798fcffb5f4e25d33c068e5/type.go#L225

**Comment by TcM1911** [comment]
Value never assigned in the constructor: https://github.com/goretk/pygore/blob/c69b56abc8401fc4e99d09fce0b190d27bd082e9/pygore/lib.py#L215
